- type: dungeonConfig
  id: Geneticore
  data:
    colors:
      Decals: "#D381C996"
    entities:
      Cabling: CableApcExtension
      CornerWalls: WallMining
      Walls: WallMining
    spawnGroups:
      CornerClutter: BaseClutter
      Entrance: GeneticoreAirlock
      EntranceFlank: GeneticoreWindow
      Junction: GeneticoreAirlock
      WallMounts: ScienceLabsWalls
      Window: GeneticoreWindow
    tiles:
      FallbackTile: FloorDark
    whitelists:
      Rooms:
        tags:
        - Geneticore
  layers:
  - !type:PrototypeDunGen
    proto: PlanetBase

# Spawn groups
# Basic
- type: entitySpawnEntry
  id: GeneticoreWindow
  entries:
  - id: Grille
  - id: BorderedReinforcedWindow

- type: entitySpawnEntry
  id: GeneticoreAirlock
  entries:
  - id: CableApcExtension
  - id: AirlockMiningGlass
