using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.ReadyManifest.UI;

[GenerateTypedNameReferences]
public sealed partial class ReadyManifestEntry : GridContainer
{
    private static readonly Color EmptyColor = Color.Yellow;
    private static readonly Color TakenColor = Color.White;

    public ReadyManifestEntry()
    {
        RobustXamlLoader.Load(this);
    }
    public ReadyManifestEntry(
        JobPrototype job,
        int jobCount,
        IPrototypeManager prototypeManager,
        SpriteSystem spriteSystem)
    {
        RobustXamlLoader.Load(this);
        EntryTitle.SetMessage(job.LocalizedName + ":");

        var jobIcon = prototypeManager.Index(job.Icon);
        EntryIcon.Texture = spriteSystem.Frame0(jobIcon.Icon);

        ReadyCount.SetMessage(jobCount.ToString(), null, jobCount > 0 ? TakenColor : EmptyColor);
    }
}
