# HoS
- type: loadout
  id: HoSEnvirosuitJumpsuit
  effects:
  - !type:GroupLoadoutEffect
    proto: EffectSpeciesPlasmaman
  equipment:
    jumpsuit: ClothingUniformEnvirosuitHoS

- type: loadout
  id: HoSEnvirosuitHead
  effects:
  - !type:GroupLoadoutEffect
    proto: EffectSpeciesPlasmaman
  equipment:
    head: ClothingHeadEnvirosuitHoS

# Warden
- type: loadout
  id: WardenEnvirosuitJumpsuit
  effects:
  - !type:GroupLoadoutEffect
    proto: EffectSpeciesPlasmaman
  equipment:
    jumpsuit: ClothingUniformEnvirosuitWarden

- type: loadout
  id: WardenEnvirosuitHead
  effects:
  - !type:GroupLoadoutEffect
    proto: EffectSpeciesPlasmaman
  equipment:
    head: ClothingHeadEnvirosuitWarden

# Security
- type: loadout
  id: SecurityEnvirosuitJumpsuit
  effects:
  - !type:GroupLoadoutEffect
    proto: EffectSpeciesPlasmaman
  equipment:
    jumpsuit: ClothingUniformEnvirosuitSecurity

- type: loadout
  id: SecurityEnvirosuitHead
  effects:
  - !type:GroupLoadoutEffect
    proto: EffectSpeciesPlasmaman
  equipment:
    head: ClothingHeadEnvirosuitSecurity

# Detective
- type: loadout
  id: ForensicEnvirosuitGloves
  effects:
  - !type:GroupLoadoutEffect
    proto: EffectSpeciesPlasmaman
  equipment:
    gloves: ClothingHandsEnvirosuitForensic
