# Additional harmony security statuses
- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconMonitor
  icon:
    sprite: /Textures/_Harmony/Interface/Misc/security_icons.rsi
    state: hud_monitor

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconSearch
  icon:
    sprite: /Textures/_Harmony/Interface/Misc/security_icons.rsi
    state: hud_search
