- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  special:
  - !type:NotifyDepartmentSpecial
    notify_text: job-prisoner-sec-notify-text
    radio_channel: Security
  - !type:AddImplantSpecial #Umbra Change - Prisoners will start with tracking inplants.
    implants: [ TrackingImplant ] #Umbra Change

- type: startingGear
  id: PrisonerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: PrisonerPDA
    ears: ClothingHeadsetGrey
