- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Atlas
  - Amber
  - Bagel
  - Box
  - ClusterPrime # Umbra: Cluster Replacement
  - Cog
  - Core
  - Fland
  #- Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Saltern
  - Packed
  #- Reach # Umbra: Derotated map.
  - Train
