- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Atlas
  - Amber
  - Bagel
  - Box
  - ClusterPrime # Umbra: Cluster Replacement
  - Convex
  - Core
  - Elkridge
  - Fland
  #- Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  #- Saltern # Umbra: Derotated map.
  - Packed
  - Plasma
  #- Reach # Umbra: Derotated map.
  - Train
