- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Atlas
  - Bagel
  - Box
  - ClusterPrime
  - Cog
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Saltern
  - Packed
  #- Reach # Umbra: Derotated map.
  - Train
