using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class ForgeSignatureWindow : DefaultWindow
{
    public event Action<string>? OnSignatureChanged;

    private bool _focused;
    private string _signature = string.Empty;

	public ForgeSignatureWindow()
	{
        RobustXamlLoader.Load(this);

        SignatureLineEdit.OnTextChanged += e =>
        {
            _signature = e.Text;
            OnSignatureChanged?.Invoke(_signature);
        };

        SignatureLineEdit.OnFocusEnter += _ => _focused = true;
        SignatureLineEdit.OnFocusExit += _ =>
        {
            _focused = false;
            SignatureLineEdit.Text = _signature;
        };
	}

	public void SetCurrentSignature(string signature)
	{
        if (signature == _signature)
            return;

        _signature = signature;
        if (!_focused)
            SignatureLineEdit.Text = signature;
	}

    public void SetMaxSignatureLength(int maxLength)
    {
        SignatureLineEdit.IsValid = s => s.Length <= maxLength;
    }

}


