- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  #requirements: # Umbra: Use Umbra Roletimers over Wizden.
  #  - !type:DepartmentTimeRequirement
  #    department: Cargo
  #    time: 9000 # 2.5 hrs
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
#    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist # CD unique
    id: SalvagePDA
    ears: ClothingHeadsetCargo
  #storage:
    #back:
    #- Stuff
