# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10800 # 3 hrs
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hrs
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  applyTraits: false
  # CD: Skip records
  special:
    - !type:AddComponentSpecial
      components:
        - type: SkipLoadingCharacterRecords
  # end CD

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  applyTraits: false
  # CD: Skip records
  special:
    - !type:AddComponentSpecial
      components:
        - type: SkipLoadingCharacterRecords
  # end CD
