# No idea why it's in sci but we ball.
# Why is this one file?
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
    - !type:DepartmentTimeRequirement # Umbra: Use Umbra Roletimers over Wizden.
      department: Command
      time: 10800 # 3 hrs
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hrs
  #- !type:RoleTimeRequirement
  #  role: JobBorg
  #  time: 18000  # 5 hrs
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  jobPreviewEntity: PlayerStationAiPreview
  applyTraits: false
  # CD: Skip records
  special:
    - !type:AddComponentSpecial
      components:
        - type: SkipLoadingCharacterRecords
  # end CD

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  #requirements: # Umbra: Use Umbra Roletimers over Wizden.
  #  - !type:OverallPlaytimeRequirement
  #    time: 36000 # 10 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  applyTraits: false
  # CD: Skip records
  special:
    - !type:AddComponentSpecial
      components:
        - type: SkipLoadingCharacterRecords
  # end CD
