- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:OverallPlaytimeRequirement # Umbra: Use Umbra Roletimers over Wizden.
      time: 21600 # 6 hrs
  #- !type:RoleTimeRequirement
  #  role: JobScientist
  #  time: 18000 #5 hrs
  #- !type:DepartmentTimeRequirement
  #  department: Science
  #  time: 36000 #10 hrs
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  # - Brig # Umbra - Removed
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash
