name: Publish

concurrency:
  group: publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publish
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0.100

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64 --platform osx-x64 --platform linux-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Update Build Info
      run: Tools/gen_build_info.py

    - name: Shuffle files around
      run: |
        mkdir "release/${{ github.sha }}"
        mv release/*.zip "release/${{ github.sha }}"

    - name: Upload files to game server
      uses: appleboy/scp-action@master
      with:
        host: sector-umbra.net
        port: 3489
        username: staticfiles
        key: ${{ secrets.UMBRA_BUILD_PUSH_KEY }}
        passphrase: ${{ secrets.UMBRA_BUILD_PUSH_PASSPHRASE }}
        source: "release/${{ github.sha }}"
        target: "/home/staticfiles/workdir/"
        strip_components: 1

    - name: Update manifest JSON
      uses: appleboy/ssh-action@master
      with:
        host: sector-umbra.net
        port: 3489
        username: staticfiles
        key: ${{ secrets.UMBRA_BUILD_PUSH_KEY }}
        passphrase: ${{ secrets.UMBRA_BUILD_PUSH_PASSPHRASE }}
        script: "/home/staticfiles/workdir/ingest.sh ${{ github.sha }}"

    # - name: Publish changelog (Discord)
    #   run: Tools/actions_changelogs_since_last_run.py
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}

    # - name: Publish changelog (RSS)
    #   run: Tools/actions_changelog_rss.py
    #   env:
    #     CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}
